### ISSUE TITLE
Font too big using p-touch 1230pc (12mm)

### ISSUE THREAD

**Issue by kelvan** [dradermacher/ptouch-print#1]
Installed 1.3.1 through aur
Shows "choosing font size 55"
Text cut off at the bottom
--fontsize ignored

**Comment by dradermacher** [comment]
The PKGBUILD from AUR did not use the source from github here, but the (outdated) source from sourceforge. I corrected this just now. So your issue is related to AUR , not the source found here.
The current version found here (1.3.2) has working support for the switch "--fontsize".
Text being cut of at the bottom is a problem I have been chasing for a while. Which font do you use,
and which characters are being cut of? Could you please verify if this problem still exists in the current version? Thanks.

**Comment by kelvan** [comment]
Thanks for the fast reply, I'll test the new version when I'm back home.
I didn't set any specific font, not sure what default font is used, maybe Cantarell.
I hope I have enough tape left to test all chars.

**Comment by dradermacher** [comment]
No need to waste lots of tape to check that, please use the option --writepng first to see if it is rendered incorrect (which is what I think).
